// components/ui/Panel.jsx
import React from 'react';
/* Surface cards — .panel sheen / .glass frost from effects.css; radii 1rem card, 1.5rem feature */
export function Panel({ variant = 'panel', glow = false, padding = 24, radius, className = '', style, children, ...rest }) {
  const surface = variant === 'glass' ? 'glass' : 'panel';
  const glowCls = glow === 'sm' ? 'glow-blue glow-blue-sm' : glow ? 'glow-blue' : '';
  return (
    <div className={[surface, glowCls, className].filter(Boolean).join(' ')}
      style={{ borderRadius: radius ?? (variant === 'feature' ? 'var(--radius-feature)' : 'var(--radius-card)'), padding, ...style }} {...rest}>
      {children}
    </div>
  );
}

// templates/vue-package/src/components/ui/Panel.vue
<script setup lang="ts">
/**
 * Surface card — `.panel` diagonal-sheen content card, `.glass` frosted tile,
 * or `feature` (panel surface at the larger 1.5rem radius).
 * Vue port of the React mirror's Panel (components/ui/Panel.jsx).
 */
import { computed } from 'vue'

const props = withDefaults(
  defineProps<{
    /** panel = content card, glass = frosted floating tile, feature = panel at 1.5rem radius */
    variant?: 'panel' | 'glass' | 'feature'
    /** Corner azure glow: true = .glow-blue, 'sm' = .glow-blue-sm */
    glow?: boolean | 'sm'
    padding?: number | string
    /** Override border-radius (defaults to --radius-card / --radius-feature) */
    radius?: number | string
  }>(),
  { variant: 'panel', glow: false, padding: 24 },
)

const cls = computed(() => [
  props.variant === 'glass' ? 'glass' : 'panel',
  props.glow === 'sm' ? 'glow-blue glow-blue-sm' : props.glow ? 'glow-blue' : '',
])

const style = computed(() => ({
  borderRadius:
    props.radius ?? (props.variant === 'feature' ? 'var(--radius-feature)' : 'var(--radius-card)'),
  padding: typeof props.padding === 'number' ? `${props.padding}px` : props.padding,
}))
</script>

<template>
  <div :class="cls" :style="style">
    <slot />
  </div>
</template>
