// templates/vue-package/src/components/ui/DateRangeEditor.vue
<script setup lang="ts">
/**
 * Relative time-range editor — .fm-control trigger with calendar glyph opening a preset
 * panel (前一周/前一月/前一年 …) with a computed-range readout and 取消/应用 actions.
 */
import { computed, ref, watch } from 'vue'
import { Calendar } from 'lucide-vue-next'
import Popover from './Popover.vue'
import RadioGroup, { type RadioOption } from './RadioGroup.vue'
import Button from './Button.vue'

const props = withDefaults(
  defineProps<{
    presets?: RadioOption[]
    /** Readout under the presets — a string, or a function of the draft value */
    rangeText?: string | ((draft: string | undefined) => string | undefined)
    title?: string
    width?: number
    placeholder?: string
  }>(),
  { presets: () => [], title: '编辑时间范围', width: 300, placeholder: '选择时间范围' },
)

const model = defineModel<string>()

const open = ref(false)
const draft = ref(model.value)
watch(open, (v) => {
  if (v) draft.value = model.value
})

const current = computed(() => props.presets.find((p) => p.value === model.value))
const readout = computed(() =>
  typeof props.rangeText === 'function' ? props.rangeText(draft.value) : props.rangeText,
)

function apply() {
  model.value = draft.value
  open.value = false
}
</script>

<template>
  <Popover v-model:open="open" :width="width">
    <template #anchor>
      <button
        type="button"
        class="fm-control"
        aria-haspopup="dialog"
        :aria-expanded="open"
        style="display: flex; align-items: center; gap: 8px; text-align: left; cursor: pointer"
      >
        <span :style="{ flex: 1, color: current ? 'var(--color-bone)' : 'var(--color-mist)' }">
          {{ current ? current.label : placeholder }}
        </span>
        <span style="display: inline-flex; color: var(--color-mist)"><Calendar :size="14" :stroke-width="1.75" /></span>
      </button>
    </template>
    <div style="display: flex; flex-direction: column; gap: 12px; text-align: left">
      <span style="font-size: 13px; font-weight: 500; color: var(--color-bone)">{{ title }}</span>
      <RadioGroup v-model="draft" :options="presets" />
      <span v-if="readout" style="font-size: 11px; letter-spacing: 0.02em; color: var(--color-mist)">{{ readout }}</span>
      <div style="display: flex; justify-content: flex-end; gap: 8px">
        <Button variant="ghost" size="sm" @click="open = false">取消</Button>
        <Button size="sm" @click="apply">应用</Button>
      </div>
    </div>
  </Popover>
</template>

// components/ui/DateRangeEditor.jsx
import React from 'react';
import { Icon } from '../core/Icon.jsx';
import { Popover } from './Popover.jsx';
import { RadioGroup } from './Radio.jsx';
import { Button } from '../core/Button.jsx';
/* Relative time-range editor — .fm-control trigger with calendar glyph opening a preset
   panel (前一周/前一月/前一年 …) with a computed-range readout and 取消/应用 actions. */
export function DateRangeEditor({ presets = [], value, onChange, rangeText, title = '编辑时间范围', width = 300, placeholder = '选择时间范围', style }) {
  const [open, setOpen] = React.useState(false);
  const [draft, setDraft] = React.useState(value);
  React.useEffect(() => { if (open) setDraft(value); }, [open]);
  const current = presets.find(p => p.value === value);
  const readout = typeof rangeText === 'function' ? rangeText(draft) : rangeText;
  return (
    <Popover open={open} onOpenChange={setOpen} width={width} style={style}
      anchor={
        <button type="button" className="fm-control" aria-haspopup="dialog" aria-expanded={open}
          style={{ display: 'flex', alignItems: 'center', gap: 8, textAlign: 'left', cursor: 'pointer' }}>
          <span style={{ flex: 1, color: current ? 'var(--color-bone)' : 'var(--color-mist)' }}>{current ? current.label : placeholder}</span>
          <span style={{ display: 'inline-flex', color: 'var(--color-mist)' }}><Icon name="calendar" size={14} /></span>
        </button>
      }>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12, textAlign: 'left' }}>
        <span style={{ fontSize: 13, fontWeight: 500, color: 'var(--color-bone)' }}>{title}</span>
        <RadioGroup value={draft} onChange={setDraft} options={presets} />
        {readout ? <span style={{ fontSize: 11, letterSpacing: '0.02em', color: 'var(--color-mist)' }}>{readout}</span> : null}
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
          <Button variant="ghost" size="sm" onClick={() => setOpen(false)}>取消</Button>
          <Button size="sm" onClick={() => { if (onChange) onChange(draft); setOpen(false); }}>应用</Button>
        </div>
      </div>
    </Popover>
  );
}
