// templates/vue-package/src/components/ui/Pagination.vue
<script setup lang="ts">
/** Pill pagination — 28px circles, current page lifts to bone 8% like the active tab. `v-model:page`. */
import { computed, ref } from 'vue'
import { ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight } from 'lucide-vue-next'

const props = withDefaults(
  defineProps<{
    pageCount?: number
    siblings?: number
    showEnds?: boolean
  }>(),
  { pageCount: 1, siblings: 1, showEnds: true },
)

const page = defineModel<number>('page', { default: 1 })
const hovered = ref<string | null>(null)

function go(p: number) {
  if (p >= 1 && p <= props.pageCount && p !== page.value) page.value = p
}

const pages = computed<(number | string)[]>(() => {
  const out: (number | string)[] = [1]
  const lo = Math.max(2, page.value - props.siblings)
  const hi = Math.min(props.pageCount - 1, page.value + props.siblings)
  if (lo > 2) out.push('…l')
  for (let p = lo; p <= hi; p++) out.push(p)
  if (hi < props.pageCount - 1) out.push('…r')
  if (props.pageCount > 1) out.push(props.pageCount)
  return out
})

function btnStyle(key: string, active: boolean, disabled: boolean) {
  const hover = hovered.value === key
  return {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '28px',
    height: '28px',
    padding: '0 6px',
    borderRadius: '999px',
    cursor: disabled ? 'not-allowed' : 'pointer',
    fontFamily: 'var(--font-sans)',
    fontSize: '12px',
    fontWeight: 500,
    fontVariantNumeric: 'tabular-nums',
    border: `1px solid ${
      active
        ? 'color-mix(in srgb, var(--color-bone) 15%, transparent)'
        : hover && !disabled
          ? 'color-mix(in srgb, var(--color-azure) 30%, transparent)'
          : 'transparent'
    }`,
    background: active ? 'color-mix(in srgb, var(--color-bone) 8%, transparent)' : 'transparent',
    color: active ? 'var(--color-bone)' : hover && !disabled ? 'var(--color-bone-soft)' : 'var(--color-bone-dim)',
    opacity: disabled ? 0.4 : 1,
    transition: 'all 0.2s var(--ease-calm)',
  }
}
</script>

<template>
  <nav aria-label="分页" style="display: inline-flex; align-items: center; gap: 4px">
    <button
      v-if="showEnds"
      type="button"
      aria-label="第一页"
      :disabled="page <= 1"
      :style="btnStyle('first', false, page <= 1)"
      @click="go(1)"
      @mouseenter="hovered = 'first'"
      @mouseleave="hovered = null"
    ><ChevronsLeft :size="13" :stroke-width="1.75" /></button>
    <button
      type="button"
      aria-label="上一页"
      :disabled="page <= 1"
      :style="btnStyle('prev', false, page <= 1)"
      @click="go(page - 1)"
      @mouseenter="hovered = 'prev'"
      @mouseleave="hovered = null"
    ><ChevronLeft :size="13" :stroke-width="1.75" /></button>
    <template v-for="p in pages" :key="p">
      <span
        v-if="typeof p === 'string'"
        style="min-width: 20px; text-align: center; font-size: 12px; color: var(--color-mist)"
      >…</span>
      <button
        v-else
        type="button"
        :aria-label="`第 ${p} 页`"
        :aria-current="p === page ? 'page' : undefined"
        :style="btnStyle(`p${p}`, p === page, false)"
        @click="go(p)"
        @mouseenter="hovered = `p${p}`"
        @mouseleave="hovered = null"
      >{{ p }}</button>
    </template>
    <button
      type="button"
      aria-label="下一页"
      :disabled="page >= pageCount"
      :style="btnStyle('next', false, page >= pageCount)"
      @click="go(page + 1)"
      @mouseenter="hovered = 'next'"
      @mouseleave="hovered = null"
    ><ChevronRight :size="13" :stroke-width="1.75" /></button>
    <button
      v-if="showEnds"
      type="button"
      aria-label="最后一页"
      :disabled="page >= pageCount"
      :style="btnStyle('last', false, page >= pageCount)"
      @click="go(pageCount)"
      @mouseenter="hovered = 'last'"
      @mouseleave="hovered = null"
    ><ChevronsRight :size="13" :stroke-width="1.75" /></button>
  </nav>
</template>

// components/ui/Pagination.jsx
import React from 'react';
import { Icon } from '../core/Icon.jsx';
/* Pill pagination — 28px circles, current page lifts to bone 8% like the active tab */
function PageButton({ children, active = false, disabled = false, onClick, label }) {
  const [hover, setHover] = React.useState(false);
  return (
    <button type="button" aria-label={label} aria-current={active ? 'page' : undefined} disabled={disabled}
      onClick={onClick} onMouseEnter={() => setHover(true)} onMouseLeave={() => setHover(false)}
      style={{
        display: 'inline-flex', alignItems: 'center', justifyContent: 'center', minWidth: 28, height: 28,
        padding: '0 6px', borderRadius: 999, cursor: disabled ? 'not-allowed' : 'pointer',
        fontFamily: 'var(--font-sans)', fontSize: 12, fontWeight: 500, fontVariantNumeric: 'tabular-nums',
        border: `1px solid ${active ? 'color-mix(in srgb, var(--color-bone) 15%, transparent)' : hover && !disabled ? 'color-mix(in srgb, var(--color-azure) 30%, transparent)' : 'transparent'}`,
        background: active ? 'color-mix(in srgb, var(--color-bone) 8%, transparent)' : 'transparent',
        color: active ? 'var(--color-bone)' : hover && !disabled ? 'var(--color-bone-soft)' : 'var(--color-bone-dim)',
        opacity: disabled ? 0.4 : 1, transition: 'all 0.2s var(--ease-calm)',
      }}>
      {children}
    </button>
  );
}
export function Pagination({ page = 1, pageCount = 1, onChange, siblings = 1, showEnds = true, style }) {
  const go = (p) => { if (onChange && p >= 1 && p <= pageCount && p !== page) onChange(p); };
  const pages = [];
  const lo = Math.max(2, page - siblings), hi = Math.min(pageCount - 1, page + siblings);
  pages.push(1);
  if (lo > 2) pages.push('…l');
  for (let p = lo; p <= hi; p++) pages.push(p);
  if (hi < pageCount - 1) pages.push('…r');
  if (pageCount > 1) pages.push(pageCount);
  return (
    <nav aria-label="分页" style={{ display: 'inline-flex', alignItems: 'center', gap: 4, ...style }}>
      {showEnds ? <PageButton label="第一页" disabled={page <= 1} onClick={() => go(1)}><Icon name="chevrons-left" size={13} /></PageButton> : null}
      <PageButton label="上一页" disabled={page <= 1} onClick={() => go(page - 1)}><Icon name="chevron-left" size={13} /></PageButton>
      {pages.map(p => typeof p === 'string'
        ? <span key={p} style={{ minWidth: 20, textAlign: 'center', fontSize: 12, color: 'var(--color-mist)' }}>…</span>
        : <PageButton key={p} active={p === page} label={`第 ${p} 页`} onClick={() => go(p)}>{p}</PageButton>)}
      <PageButton label="下一页" disabled={page >= pageCount} onClick={() => go(page + 1)}><Icon name="chevron-right" size={13} /></PageButton>
      {showEnds ? <PageButton label="最后一页" disabled={page >= pageCount} onClick={() => go(pageCount)}><Icon name="chevrons-right" size={13} /></PageButton> : null}
    </nav>
  );
}
