// templates/vue-package/src/components/ui/SectionHeading.vue
<script setup lang="ts">
import Reveal from './Reveal.vue'

withDefaults(
  defineProps<{
    eyebrow?: string
    title: string
    copy?: string
    align?: 'center' | 'left'
  }>(),
  { align: 'center' },
)
</script>

<template>
  <div :class="['flex flex-col gap-5', align === 'center' ? 'items-center text-center' : 'items-start text-left']">
    <Reveal v-if="eyebrow" :y="16">
      <div class="flex items-center gap-2.5">
        <span class="h-px w-6 bg-azure/50" />
        <span class="eyebrow text-azure">{{ eyebrow }}</span>
      </div>
    </Reveal>

    <Reveal :y="20" :delay="0.06">
      <h2
        :class="[
          'text-balance text-3xl font-bold leading-tight tracking-tight text-bone sm:text-4xl lg:text-[2.7rem]',
          align === 'center' ? 'mx-auto max-w-2xl' : 'max-w-3xl',
        ]"
      >
        {{ title }}
      </h2>
    </Reveal>

    <Reveal v-if="copy" :y="20" :delay="0.12">
      <p
        :class="[
          'text-[15px] leading-relaxed text-bone-dim sm:text-base',
          align === 'center' ? 'mx-auto max-w-2xl' : 'max-w-xl',
        ]"
      >
        {{ copy }}
      </p>
    </Reveal>
  </div>
</template>

// components/core/SectionHeading.jsx
import React from 'react';
/* Section heading: eyebrow with dash, bold title, dim copy — from SectionHeading.vue */
export function SectionHeading({ eyebrow, title, copy, align = 'center' }) {
  const center = align === 'center';
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20, alignItems: center ? 'center' : 'flex-start', textAlign: center ? 'center' : 'left' }}>
      {eyebrow ? (
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <span style={{ height: 1, width: 24, background: 'color-mix(in srgb, var(--color-azure) 50%, transparent)' }}></span>
          <span className="eyebrow" style={{ color: 'var(--color-azure)' }}>{eyebrow}</span>
        </div>
      ) : null}
      <h2 style={{ margin: 0, maxWidth: center ? '42rem' : '48rem', fontSize: 'var(--text-h2)', fontWeight: 700, lineHeight: 1.15, letterSpacing: '-0.025em', color: 'var(--color-bone)', textWrap: 'balance' }}>{title}</h2>
      {copy ? <p style={{ margin: 0, maxWidth: center ? '42rem' : '36rem', fontSize: 15, lineHeight: 1.625, color: 'var(--color-bone-dim)' }}>{copy}</p> : null}
    </div>
  );
}
